name: Deploy Pages

on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install Pillow
      - name: Download Original Image from Release
        run: wget -q -O Kunyu_Wanguo_Quantu.jpg "https://github.com/ychenzgithub/MapAppreciation/releases/download/v1.0/Kunyu_Wanguo_Quantu.jpg"
      - name: Generate Tiles
        run: python3 tile_generator.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
  
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
